### ISSUE TITLE
Epic: NJsonSchema v11

### ISSUE THREAD

**Issue by RicoSuter** [RicoSuter/NJsonSchema#1045]
Breaking changes: 

- [x] Change project/package structure to use System.Text.Json serialization in the future and move Newtonsoft.Json schema generation into it's own dedicated package

Possible Features: 

- [ ] Support Open API v3 extensions
- [ ] Draft v6 and v7 support: https://github.com/RSuter/NJsonSchema/issues/574
- Change Record type ordering: https://github.com/RicoSuter/NJsonSchema/pull/1055
