### ISSUE TITLE
Epic: NJsonSchema v10

### ISSUE THREAD

**Issue by RicoSuter** [RicoSuter/NJsonSchema#507]
Breaking changes: 

- [x] Rename JsonSchema4 to JsonSchema (?)

Change setting defaults (breaking changes):

- [x] Set default of GenerateConstructorInterface to true
- [x] Set default TypeScript version to 2.7
- [x] Change defaults of Array/Dictionary types (ICollection/IDictionary)
- [x] Change default of GenerateJsonMethods to false (CSharp)
- [ ] ~~Set default of AllowReferencesWithProperties to true (more tools expected this) (?), https://github.com/RSuter/NJsonSchema/issues/531~~

Epics planned for this release: 

- [x] New template engine (enabled by default): https://github.com/RSuter/NSwag/issues/263
- [x] Multi file support: https://github.com/RSuter/NJsonSchema/issues/514

**Comment by RicoSuter** [comment]
Default settings: https://github.com/RicoSuter/NJsonSchema/pull/806
